name: drawer-open-rotate

task_name: ${name}

shape_meta: &shape_meta
  obs:
    img:
      shape: [3, 128, 128]
      type: rgb
    agent_pos:
      shape: [9]
      type: low_dim
  # action:
  #   shape: [4]
  action:
    shape: [8]

env_runner:
  _target_: diffusion_policy.env_runner.metaworld_runner.MetaworldRunner
  eval_episodes: 20
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  n_envs: null
  n_train: null
  n_test: null
  task_name: ${task_name}
  device: ${training.device}
  use_point_crop: ${policy.use_point_crop}

dataset:
  _target_: diffusion_policy.dataset.metaworld_dataset.MetaworldDataset
  zarr_path: /short-trajectory/drawer-rotate-move-2000-v2-v002-d40/metaworld_drawer-open-rotate_expert.zarr
  # zarr_path: /3D-Diffusion-Policy/3D-Diffusion-Policy/data/metaworld_drawer-open_expert.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  # max_train_episodes: 90
