name: peg-insert-side

task_name: ${name}

shape_meta: &shape_meta
  obs:
    img:
      shape: [3, 128, 128]
      type: rgb
  action:
    shape: [4]

env_runner:
  _target_: diffusion_policy.env_runner.metaworld_runner.MetaworldRunner
  eval_episodes: 20
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  n_envs: null
  n_train: null
  n_test: null
  task_name: ${task_name}
  device: ${training.device}
  use_point_crop: ${policy.use_point_crop}

dataset:
  _target_: diffusion_policy.dataset.metaworld_dataset.MetaworldDataset
  zarr_path: /peg-insert-new-camera/5000-m003-c05-o003-25-80/metaworld_peg-insert-side_expert.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  # # max_train_episodes: 90
